spring.application.name=nightshift

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=nightshift;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver