### Open incident

POST http://localhost:8080/api/servers/1/incidents
Content-Type: application/json

{
  "title": "Database response time is high"
}


### Get open incidents

GET http://localhost:8080/api/incidents/open


### Resolve incident

PATCH http://localhost:8080/api/incidents/1/resolve


### Check servers

GET http://localhost:8080/api/servers